### ISSUE TITLE
Next-range sent after requesting whole content

### ISSUE THREAD

**Issue by PierreGUI** [chordify/haskell-servant-pagination#3]
Given a set of 100 items, requesting the whole set with a header `range` such as `modified_at;limit 100` will have a `next-range` alike the following: `modified_at [date];limit 100;offset 100;order desc` (any request with the latter should have empty response and no `next-range`).

Wouldn't it be correct to send no `next-range` in the first response already, as `total-count` and `offset` are the same?

**Comment by KtorZ** [comment]
The issue is a bit more difficult. For that specific use-case, it would work indeed. However, since you can start a range from any resource, it isn't possible to know (without querying it and searching for its index) where a resource is and how many resources are positioned before. 

Though, we could potentially identify cases where indeed, with the offset only, we are able to tell whether or not it makes sense to return a `Next-Range`.

**Comment by PierreGUI** [comment]
Indeed, I think in case we'd be using a combination of limit+offset and it's obviously above total count, then no `next-range` should be returned, avoiding an extra call (and some frontend logic).

**Comment by mklinik** [comment]
The issue came back today. From conversation with @jbransen it seems that there are two cases.

1. The returned page has the same number of items as the `limit`. If this page happens to be the last one, servant-pagination has no way of knowing that, and generates a `Next-Range` header. This is fine.
2. The returned page has less items that `limit`. In this case no `Next-Range` header should be generated.

See this example: https://gist.github.com/mklinik/84499fb28c3d5e6122da58d1ed13d749
Even though there are only three colors in the list, and all are returned, there is a `Next-Range` header.

```
$ curl -v localhost:1337/colors
*   Trying 127.0.0.1:1337...
* Connected to localhost (127.0.0.1) port 1337 (#0)
> GET /colors HTTP/1.1
> Host: localhost:1337
> User-Agent: curl/7.80.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 206 Partial Content
< Transfer-Encoding: chunked
< Date: Wed, 08 Dec 2021 10:42:23 GMT
< Server: Warp/3.3.18
< Content-Type: application/json;charset=utf-8
< Accept-Ranges: name
< Content-Range: name Blue..Aqua
< Next-Range: name Aqua;limit 100;offset 1;order desc
<
* Connection #0 to host localhost left intact
[{"hex":"#0000ff","name":"Blue","rgb":[0,0,255]},{"hex":"#000000","name":"Black","rgb":[0,0,0]},{"hex":"#00ffff","name":"Aqua","rgb":[0,255,255]}]
```

**Comment by tomasklingen** [comment]
> The issue came back today. From conversation with @jbransen it seems that there are two cases.
> 
> 1. The returned page has the same number of items as the `limit`. If this page happens to be the last one, servant-pagination has no way of knowing that, and generates a `Next-Range` header. This is fine.

What is the reason for this? I would guess that in a DB query we can get a total count and see if this was in fact the last page/range.
